---
- name: Clone scout
  hosts: server
  gather_facts: false

  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/washu-tag/scout-gh-test.git
        dest: '{{ scout_repo_dir }}'
        version: feb-17-ci
